# Generated by Django 3.1 on 2020-09-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_card_agent'),
        ('account', '0004_remove_account_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cards',
        ),
        migrations.AddField(
            model_name='account',
            name='cards',
            field=models.ManyToManyField(to='card.Card', verbose_name='cards'),
        ),
    ]
