# Generated by Django 3.1 on 2020-09-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_card_agent'),
        ('account', '0006_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cards',
            field=models.ManyToManyField(to='card.Card'),
        ),
    ]
