# Generated by Django 3.1.1 on 2020-09-13 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        ('card', '0001_initial'),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(max_length=100, null=True)),
                ('offer_body', models.TextField()),
                ('discount', models.BooleanField(default=False, null=True)),
                ('cashback', models.BooleanField(default=False, null=True)),
                ('value', models.CharField(max_length=50, null=True)),
                ('mintransact', models.IntegerField(null=True)),
                ('maxben', models.IntegerField(null=True)),
                ('start', models.DateTimeField(null=True)),
                ('expiry', models.DateTimeField(null=True)),
                ('ccdc', models.CharField(max_length=3, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.URLField(blank=True, max_length=300, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('trending', models.BooleanField(default=False, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('criteria', models.JSONField(blank=True, null=True)),
                ('tnc', models.URLField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank', verbose_name='bank')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.card', verbose_name='card')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor', verbose_name='vendor')),
            ],
        ),
    ]
