# Generated by Django 3.1 on 2020-09-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_image',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
