# Generated by Django 3.1 on 2020-09-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_card_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='debit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='tier',
            field=models.IntegerField(default=5),
        ),
    ]
