# Generated by Django 3.1 on 2020-09-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_auto_20200903_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='agent',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
